/* Built-in editorial destination data for EasierPride. No personal visitor data is collected. */
window.ABHA_PLACES = [
  { id: "soudah", category: "nature", time: "morning", image: "assets/images/asir-mountains.jpg", imageAlt: { ar: "جبال عسير الخضراء تحت السحاب", en: "Green Asir mountains beneath drifting clouds" }, name: { ar: "منتزه السودة", en: "Al Soudah Park" }, tagline: { ar: "ضبابٌ بارد، مدرجاتٌ خضراء، وإطلالات لا تنتهي.", en: "Cool mist, green terraces, and views that keep going." }, best: ["may", "jun", "jul", "aug", "sep"], maps: "https://www.google.com/maps/search/?api=1&query=Al+Soudah+Park+Abha", note: { ar: "اذهب باكراً؛ السحب أجمل قبل الظهر.", en: "Go early — the cloud cover is loveliest before noon." } },
  { id: "aser-national-park", category: "nature", time: "morning", image: "assets/images/asir-mountains.jpg", imageAlt: { ar: "جبال عسير الخضراء", en: "Asir highland scenery" }, name: { ar: "منتزه عسير الوطني", en: "Aseer National Park" }, tagline: { ar: "طريقٌ بين العرعر وهواء الجبل المنعش.", en: "Juniper-lined roads and bracing mountain air." }, best: ["apr", "may", "jun", "jul", "aug", "sep", "oct"], maps: "https://www.google.com/maps/search/?api=1&query=Aseer+National+Park+Abha", note: { ar: "خذ جاكيتاً خفيفاً حتى في الصيف.", en: "Bring a light jacket, even in summer." } },
  { id: "abu-khayal", category: "nature", time: "evening", image: "assets/images/abha-view.jpg", imageAlt: { ar: "إطلالة مرتفعة على مدينة أبها", en: "An elevated view over Abha city" }, name: { ar: "منتزه أبو خيال", en: "Abu Khayal Park" }, tagline: { ar: "مكان هادئ لغروبٍ جميل فوق أبها.", en: "A quiet green pause for a beautiful Abha sunset." }, best: ["oct", "nov", "dec", "jan", "feb", "mar", "apr"], maps: "https://www.google.com/maps/search/?api=1&query=Abu+Khayal+Park+Abha", note: { ar: "مثالي قبل العشاء أو لنزهة قصيرة.", en: "Perfect before dinner or for a short stroll." } },
  { id: "rijal-almaa", category: "heritage", time: "morning", image: "assets/images/rijal-almaa.jpg", imageAlt: { ar: "منازل حجرية تقليدية في قرية رجال ألمع", en: "Traditional stone homes in Rijal Almaa village" }, name: { ar: "قرية رجال ألمع", en: "Rijal Almaa Heritage Village" }, tagline: { ar: "حكايات الحجر واللون على طريق تهامة.", en: "Stories in stone and colour on the road to Tihamah." }, best: ["oct", "nov", "dec", "jan", "feb", "mar", "apr"], maps: "https://www.google.com/maps/search/?api=1&query=Rijal+Almaa+Heritage+Village", note: { ar: "خصص نصف يوم للطريق والقرية والمتحف.", en: "Give the drive, village, and museum a relaxed half-day." } },
  { id: "al-muftaha", category: "heritage", time: "evening", image: "assets/images/rijal-almaa.jpg", imageAlt: { ar: "تكوين حجري وتراثي من منطقة عسير", en: "A heritage stone scene from the Asir region" }, name: { ar: "قرية المفتاحة", en: "Al Muftaha Village" }, tagline: { ar: "فن عسيري وألوانٌ صغيرة في قلب المدينة.", en: "Asiri art and bursts of colour in the city centre." }, best: ["jan", "feb", "mar", "apr", "may", "oct", "nov", "dec"], maps: "https://www.google.com/maps/search/?api=1&query=Al+Muftaha+Village+Abha", note: { ar: "توقف للكافيهات والفن قبل الغروب.", en: "Stop for art and cafés before the sun goes down." } },
  { id: "al-habala", category: "heritage", time: "morning", image: "assets/images/rijal-almaa.jpg", imageAlt: { ar: "منحدرات جبلية في منطقة عسير", en: "Mountain slopes in the Asir region" }, name: { ar: "قرية الحبلة", en: "Al Habala Village" }, tagline: { ar: "قرية معلّقة وحافة جبلية لا تُنسى.", en: "A hanging village with an unforgettable mountain edge." }, best: ["oct", "nov", "dec", "jan", "feb", "mar", "apr"], maps: "https://www.google.com/maps/search/?api=1&query=Al+Habala+Village+Abha", note: { ar: "تحقق من أوقات الزيارة قبل الانطلاق.", en: "Check current visiting hours before setting off." } },
  { id: "tuesday-market", category: "heritage", time: "morning", image: "assets/images/asir-mountains.jpg", imageAlt: { ar: "منظر من منطقة عسير", en: "A view from the Asir region" }, name: { ar: "سوق الثلاثاء", en: "Tuesday Market" }, tagline: { ar: "عطورٌ وتوابل وحرفٌ تُحكى بلا استعجال.", en: "Perfume, spices, and crafts — all best explored slowly." }, best: ["jan", "feb", "mar", "apr", "may", "oct", "nov", "dec"], maps: "https://www.google.com/maps/search/?api=1&query=Tuesday+Market+Abha", note: { ar: "أجمل تجربة تكون صباح الثلاثاء.", en: "The fullest experience is on Tuesday morning." } },
  { id: "souq-flavours", category: "food", time: "lunch", image: "assets/images/asiri-food.jpg", imageAlt: { ar: "منظر من منطقة عسير", en: "A view from the Asir region" }, name: { ar: "نكهات عسير في سوق الثلاثاء", en: "Asiri Flavours at Tuesday Market" }, tagline: { ar: "ابدأ بحفنة بهارات، وانتهِ بطبقٍ محلي دافئ.", en: "Start with a handful of spices, end with a warm local plate." }, best: ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"], maps: "https://www.google.com/maps/search/?api=1&query=Tuesday+Market+Abha", note: { ar: "اسأل الباعة عن العسل والبهارات المحلية.", en: "Ask vendors about local honey and spice blends." } },
  { id: "high-city", category: "food", time: "lunch", image: "assets/images/abha-cafe.jpg", imageAlt: { ar: "منظر من منطقة عسير", en: "A view from the Asir region" }, name: { ar: "كافيهات المدينة العالية", en: "High City Cafés" }, tagline: { ar: "قهوة، سحاب، وإطلالة كاملة على المرتفعات.", en: "Coffee, clouds, and a full view of the highlands." }, best: ["may", "jun", "jul", "aug", "sep", "oct"], maps: "https://www.google.com/maps/search/?api=1&query=High+City+Abha", note: { ar: "ممتازة لاستراحة الظهيرة في يوم بارد.", en: "A great midday break when the mountain air turns cool." } },
  { id: "traditional-kitchen", category: "food", time: "lunch", image: "assets/images/asiri-food.jpg", imageAlt: { ar: "منظر من منطقة عسير", en: "A view from the Asir region" }, name: { ar: "مطبخ عسير التقليدي", en: "Traditional Asiri Kitchen" }, tagline: { ar: "اطلب طبق المشاركة ودَع المذاق يقود الحديث.", en: "Order a sharing platter and let the flavours lead the conversation." }, best: ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"], maps: "https://www.google.com/maps/search/?api=1&query=Traditional+Saudi+Restaurant+Abha", note: { ar: "اطلب توصية المكان للطبق الموسمي.", en: "Ask for the venue’s seasonal house recommendation." } }
];
