(() => {
  "use strict";
  const places = window.ABHA_PLACES || [];
  if (!places.length) return;
  const monthKeys = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
  const key = "easierPride.preferences.v1";
  const words = {
    ar: { eyebrow:"دليل شخصي لمن نحب",navPlan:"خطّة يومي",heroTitleFirst:"أهلاً بك في",heroCopy:"أماكننا المفضلة، كما نحب أن نريها لصديقٍ يزورنا للمرة الأولى.",heroPillOne:"10 محطات مختارة",heroPillTwo:"على مهل، لا على عَجَل",explore:"اكتشف الأماكن",guideKicker:"دليل أبها",guideTitle:"اختَر مزاج الرحلة",guideIntro:"يومٌ بين الضباب، لقمةٌ دافئة، أو نافذةٌ على تراث عسير. اختر ما يشبهك ودع أبها تكمل الباقي.",typeLabel:"النوع",all:"الكل",nature:"طبيعة",food:"طعام",heritage:"تراث",monthLabel:"متى تزورنا؟",monthHint:"سنُظهر لك ما يزدهر في هذا الشهر",placesKicker:"خذ وقتك",placesTitle:"أماكن تستحق التوقف",planKicker:"لا وقت للتخطيط؟",planTitle:"أعطنا يوماً واحداً",planCopy:"سنرتب لك صباحاً ولُقمةً ومساءً يشبه أبها، ثم اترك مساحة للمفاجآت.",planButton:"خطّط يومي",loadExample:"إعادة الدليل التجريبي",footer:"صُنع بحبٍ لزيارةٍ أجمل إلى أبها.",backTop:"العودة للأعلى ↑",map:"افتح في الخرائط",category:{nature:"طبيعة",food:"طعام",heritage:"تراث"},months:{jan:"يناير",feb:"فبراير",mar:"مارس",apr:"أبريل",may:"مايو",jun:"يونيو",jul:"يوليو",aug:"أغسطس",sep:"سبتمبر",oct:"أكتوبر",nov:"نوفمبر",dec:"ديسمبر"},result:(n,m)=>`${n} ${n===1?"مكان":"أماكن"} مناسبة لـ ${m}`,best:m=>`الأفضل في ${m}`,empty:"لا توجد أماكن مطابقة. جرّب اختياراً آخر.",itineraryTitle:"يومك في أبها",itineraryEmpty:"اضغط «خطّط يومي» وسنقترح عليك ثلاث محطات لطيفة.",morning:"صباحاً",lunch:"وقت الغداء",evening:"مساءً" },
    en: { eyebrow:"A guide for people we love",navPlan:"Plan my day",heroTitleFirst:"Welcome to",heroCopy:"Our favourite places, shared the way we would show a friend visiting for the first time.",heroPillOne:"10 handpicked stops",heroPillTwo:"Slow down. Look closer.",explore:"Explore places",guideKicker:"Abha guide",guideTitle:"Choose your kind of day",guideIntro:"A misty morning, a warm plate, or a window into Asiri heritage. Pick your mood and let Abha do the rest.",typeLabel:"Type",all:"All",nature:"Nature",food:"Food",heritage:"Heritage",monthLabel:"When are you visiting?",monthHint:"We’ll show what shines in this month",placesKicker:"Take your time",placesTitle:"Places worth pausing for",planKicker:"No time to plan?",planTitle:"Give us one day",planCopy:"We’ll shape a morning, a meal, and an evening that feels like Abha — leave room for surprises.",planButton:"Plan my day",loadExample:"Reset demo guide",footer:"Made with love for a better visit to Abha.",backTop:"Back to top ↑",map:"Open in Maps",category:{nature:"Nature",food:"Food",heritage:"Heritage"},months:{jan:"January",feb:"February",mar:"March",apr:"April",may:"May",jun:"June",jul:"July",aug:"August",sep:"September",oct:"October",nov:"November",dec:"December"},result:(n,m)=>`${n} ${n===1?"place":"places"} fitting ${m}`,best:m=>`Best in ${m}`,empty:"No places match this combination. Try another filter.",itineraryTitle:"Your day in Abha",itineraryEmpty:"Press “Plan my day” and we’ll suggest three lovely stops.",morning:"Morning",lunch:"Lunch",evening:"Evening" }
  };
  const base={language:"ar",category:"all",month:monthKeys[new Date().getMonth()],itineraryIds:[]};
  let state;
  try { state={...base,...JSON.parse(localStorage.getItem(key))}; } catch { state={...base}; }
  if(!monthKeys.includes(state.month)||!words[state.language]) state={...base};
  const $=s=>document.querySelector(s);
  const e={grid:$("#placesGrid"),template:$("#placeTemplate"),count:$("#resultCount"),empty:$("#emptyState"),filters:$("#categoryFilters"),month:$("#monthSelect"),language:$("#languageToggle"),itinerary:$("#itinerary"),plan:$("#planButton"),reset:$("#loadExample")};
  const t=k=>words[state.language][k];
  const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{}};
  function setText(){document.documentElement.lang=state.language;document.documentElement.dir=state.language==="ar"?"rtl":"ltr";document.title=state.language==="ar"?"EasierPride | أبها على مهل":"EasierPride | Abha, at your own pace";document.querySelectorAll("[data-i18n]").forEach(n=>{if(t(n.dataset.i18n))n.textContent=t(n.dataset.i18n);});e.language.setAttribute("aria-pressed",String(state.language==="en"));e.language.setAttribute("aria-label",state.language==="ar"?"Switch to English":"التبديل إلى العربية");e.month.textContent="";monthKeys.forEach(m=>{const o=document.createElement("option");o.value=m;o.textContent=t("months")[m];o.selected=m===state.month;e.month.append(o);});}
  function matches(){return places.filter(p=>(state.category==="all"||p.category===state.category)&&p.best.includes(state.month));}
  function showPlaces(){const list=matches();e.grid.textContent="";e.count.textContent=t("result")(list.length,t("months")[state.month]);e.empty.hidden=!!list.length;e.empty.textContent=t("empty");list.forEach(p=>{const n=e.template.content.cloneNode(true),img=n.querySelector("img"),link=n.querySelector(".map-link");img.src=p.image;img.alt=p.imageAlt[state.language];n.querySelector(".place-category").textContent=t("category")[p.category];n.querySelector(".place-name").textContent=p.name[state.language];n.querySelector(".place-secondary-name").textContent=p.name[state.language==="ar"?"en":"ar"];n.querySelector(".place-tagline").textContent=p.tagline[state.language];n.querySelector(".place-note").textContent=p.note[state.language];n.querySelector(".best-badge").textContent=t("best")(t("months")[state.month]);link.href=p.maps;link.setAttribute("aria-label",`${t("map")}: ${p.name[state.language]}`);e.grid.append(n);});}
  const find=id=>places.find(p=>p.id===id);
  function choose(list,used){const pool=list.filter(p=>!used.has(p.id));if(!pool.length)return null;const item=pool[Math.floor(Math.random()*pool.length)];used.add(item.id);return item;}
  function itinerary(){const source=matches().length>=3?matches():places,used=new Set();const a=choose(source.filter(p=>p.time==="morning"),used),b=choose(source.filter(p=>p.time==="lunch"),used),c=choose(source.filter(p=>p.time==="evening"),used);state.itineraryIds=[a,b,c].filter(Boolean).map(p=>p.id);save();showItinerary();}
  function showItinerary(){const items=state.itineraryIds.map(find).filter(Boolean);e.itinerary.textContent="";if(!items.length){const box=document.createElement("div");box.className="itinerary-placeholder";box.textContent=t("itineraryEmpty");e.itinerary.append(box);return;}const h=document.createElement("h3");h.className="itinerary-title";h.textContent=t("itineraryTitle");e.itinerary.append(h);const list=document.createElement("div");list.className="itinerary-list";[t("morning"),t("lunch"),t("evening")].forEach((label,i)=>{const p=items[i];if(!p)return;const a=document.createElement("article");a.className="itinerary-item";a.innerHTML=`<img class="itinerary-image" src="${p.image}" width="76" height="76" alt=""><div><p class="itinerary-time"></p><h4 class="itinerary-place"></h4><p class="itinerary-secondary"></p></div><a class="itinerary-map" target="_blank" rel="noopener noreferrer" aria-label=""></a>`;a.querySelector("img").alt=p.imageAlt[state.language];a.querySelector(".itinerary-time").textContent=label;a.querySelector(".itinerary-place").textContent=p.name[state.language];a.querySelector(".itinerary-secondary").textContent=p.name[state.language==="ar"?"en":"ar"];const link=a.querySelector(".itinerary-map");link.href=p.maps;link.textContent="↗";link.setAttribute("aria-label",`${t("map")}: ${p.name[state.language]}`);list.append(a);});e.itinerary.append(list);}
  function showFilters(){e.filters.querySelectorAll("button").forEach(b=>{const on=b.dataset.category===state.category;b.classList.toggle("active",on);b.setAttribute("aria-pressed",String(on));});}
  function render(){setText();showFilters();showPlaces();showItinerary();}
  e.filters.addEventListener("click",ev=>{const b=ev.target.closest("button[data-category]");if(!b)return;state.category=b.dataset.category;save();showFilters();showPlaces();});e.month.addEventListener("change",()=>{state.month=e.month.value;save();showPlaces();});e.language.addEventListener("click",()=>{state.language=state.language==="ar"?"en":"ar";save();render();});e.plan.addEventListener("click",itinerary);e.reset.addEventListener("click",()=>{state={...base};save();render();document.querySelector("#guide").scrollIntoView({behavior:"smooth"});});render();
})();
